### ISSUE TITLE
فونت های دیگر

### ISSUE THREAD

**Issue by learn2007** [idreamsi/arduino-persian-reshaper#1]
سلام و خدا قوت وتشکر از کار خوبتون
میخواستم بدانم آیا امکان داره فونت سایزهای دیگر مثلا 16 هم قرار دهید یا فیلمی از نحوه ساخت فونت فارسی برای استفاده در این کتابخانه بگزارید تا حداقل ما کتابخانه شما را کامل کنیم و در اینجا قرار دهیم؟

**Comment by idreamsi** [comment]
درود بر شما
سورس بر اساس سایز 8 در 8 طراحی و نوشته شده و برای سایر فونت ها در سایزهای بالاتر نیاز به باز طراحی هست

 ضمن اینکه فونت مورد استفاده بصورت [بیت مپ](https://github.com/idreamsi/arduino-persian-reshaper/blob/master/8x8_FONT.bmp) در سورس موجوده که براحتی با نرم افزارهای طراحی فونت قابل تغییر هست.

کافیه عبارت
 8×8 Dot matrix font generator 
را جستجو کنید

برای نمونه این سایت رو ببینید
http://dotmatrixtool.com

**Comment by learn2007** [comment]
سلام شماره همراه خود را میتوانید قرار دهید تا با شما تماس بگیریم؟

**Comment by idreamsi** [comment]
با این آی دی در تلگرام در تماس باشید

https://t.me/r_mbc_r
