### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by gyroing** [idreamsi/arduino-persian-reshaper#2]
برای شکستن هر سطر و انتقال به سطر جدید در جملات ، بجای شکست در وسط یک کلمه ایجاد امکان شکست در آخرین اسپیس قبل از آن کلمه انجام شود  تا کلمات به دو نیم تقسیم نشوند 
word wrap space

**Comment by idreamsi** [comment]
مسلما این امکان قابل پیاده سازی است، سعی می کنم در اولین فرصت این امکان رو اضافه کنم

**Comment by gyroing** [comment]
ممنونم
