### ISSUE TITLE
Change font size for TFT eSPI

### ISSUE THREAD

**Issue by MShokry** [idreamsi/arduino-persian-reshaper#3]
Hi, I'm using your code it's almost working fine with me, 
I need to change the font size as I'm using a 3.5" screen and using the TFT eSPI lib

**Comment by idreamsi** [comment]
This requires rewriting the code and is currently not possible, but I think you can write on TFT displays (with custom size) by combining these two libraries ([+](https://github.com/idreamsi/u8g2-persian-reshaper),[+](https://github.com/olikraus/U8g2_for_Adafruit_GFX)).

**Comment by MShokry** [comment]
@idreamsi  Thanks for your support I used tft_eSPI
the fix is [here](https://github.com/MShokry/TFT_eFEX)
