### ISSUE TITLE
تداخل

### ISSUE THREAD

**Issue by cyberir** [idreamsi/arduino-persian-reshaper#4]
سلام و عرض ادب موقعی که OLED 128*64  دو رنگ زرد و ابی را به بورد اردینو nano متصل میکنم  و بعد ماژول rfid rc522 به اردینو متصل میکنم تابع فارسی دچار اختلال شده و نمیگذارد که ماژول rfid به درستی کار کند و موقع احراز کارت ها rfid خطا میدهد چون تابع فارسی نمیدانم چه تغییراتی اعمال میکند که این مشکل پیش می اید

**Comment by idreamsi** [comment]
درود
متاسفانه امکان تست با ماژول های RFID برام فراهم نیست.
