### ISSUE TITLE
فایل فونت

### ISSUE THREAD

**Issue by ebad84** [idreamsi/arduino-persian-reshaper#5]
سلام خسته نباشید
ممکنه فایل ttf فونت رو قرار بدید؟
برای استفاده تو micropython میخواستم. چیزی پیدا نکردم که فارسی نویسی روی OLED SSD1306 رو داشته باشه با micropython
https://github.com/peterhinch/micropython-font-to-py?tab=readme-ov-file
از این ریپو دارم سعی میکنم استفاده کنم که فایل فونت مخصوص فارسی بسازم برای استفاده

**Comment by idreamsi** [comment]
درود
خدمت شما
[q_pixia.zip](https://github.com/user-attachments/files/16202716/q_pixia.zip)

**Comment by ebad84** [comment]
متشکرم🙏
